cmd/ktctl/main.go

ref: https://github.com/alibaba/kt-connect/issues/40

#40 fixed oidc import

---

cmd/ktctl/main.go
pkg/kt/action/conect_action.go
pkg/kt/connect/connect.go
pkg/kt/connect/exchange.go
pkg/kt/connect/mesh.go
pkg/kt/connect/vpn.go
pkg/kt/util/util.go

#46 support socks5 as http proxy when vpn is not availiable

add sock5 method support

---

.gitignore
cmd/ktctl/main.go
pkg/kt/action/action.go
pkg/kt/action/conect_action.go
pkg/kt/action/exchange_action.go
pkg/kt/action/mesh_action.go
pkg/kt/connect/connect.go
pkg/kt/connect/exchange.go
pkg/kt/connect/mesh.go
pkg/kt/util/util.go

support extra labels for proxy, exchange and mesh pod

---

bin/build-shadow-dlv
docker/builder/Dockerfile
docker/shadow/Dockerfile
docker/shadow/Dockerfile_dlv
docker/shadow/run.sh
docs/zh-cn/guide/how-to-use-dns.md
pkg/proxy/dnsserver/dnsserver.go

- fix dns postfix append logic
- add dns debugger image

fix dns postfix issue

---

bin/build
bin/build-shadow
bin/build-shadow-dlv
pkg/proxy/dnsserver/dns_error.go
pkg/proxy/dnsserver/dnsserver.go

- dns server now able to resolve short domain name

support short domain name

---

.gitignore
pkg/kt/cluster/kubernetes.go
pkg/kt/command/exchange.go
pkg/kt/command/mesh.go
pkg/kt/command/run.go
pkg/kt/command/util.go
pkg/kt/connect/exchange.go
pkg/kt/connect/inbound.go
pkg/kt/connect/mesh.go
pkg/kt/options/options.go
pkg/kt/util/system.go

support expose local service to cluster
```
ktctl run localservice --port=5701 --expose
```
* --port: The port that this container exposes. If --expose is true, this is also the port used by the service
* --expose=false: If true, a public, external service is created

add new command `ktctl run`

---

pkg/kt/command/util.go

It may slove https://github.com/alibaba/kt-connect/issues/96

bug fix: add SIGKILL signal

---

docker/shadow/Dockerfile_base
docker/shadow/run.sh
go.mod
pkg/apiserver/server/server.go
pkg/apiserver/util/cluster.go
pkg/kt/cluster/kubernetes.go
pkg/kt/cluster/types.go
pkg/kt/command/connect.go
pkg/kt/command/connect_test.go
pkg/kt/command/exchange.go
pkg/kt/command/mesh.go
pkg/kt/command/run.go
pkg/kt/command/util.go
pkg/kt/connect/inbound.go
pkg/kt/connect/outbound.go
pkg/kt/connect/types.go
pkg/kt/exec/run.go
pkg/kt/exec/ssh/commands.go
pkg/kt/exec/sshuttle/commands.go
pkg/kt/options/options.go
pkg/kt/util/ssh.go
pkg/kt/util/strings.go
pkg/kt/util/system.go
pkg/kt/vars/vars.go
pkg/mockd/mock/action_mock.go
pkg/mockd/mock/connect_mock.go
pkg/mockd/mock/kubernetes_mock.go

ssh keypair dynamic

---

pkg/kt/command/connect_test.go

1. remove unnecessary args definition
2. simplify error condition statement before assertion

simplify tests

---

README.md

I really like the works you guys been doing,  just found some small issue in the English README.
This pull request introduces the following changes:
- Polished some words
- Fixed some Englis spelling and syntax errors.

Polish readme and fixed some tiny issues

---

bin/build-shadow
docs/en-us/sidebar.md
docs/en-us/troubleshoot.md
docs/zh-cn/sidebar.md
docs/zh-cn/troubleshoot.md

add document to support user shoot of network connect

docs: add troubleshoot

---

docs/index.html
web/src/routes/Service/components/Terminal/Terminal.js

resize terminal on web socket connecting

fix #144, resize terminal on web socket connecting

---

docs/en-us/cli/check.md
docs/en-us/cli/connect.md
docs/en-us/cli/dashboard.md
docs/en-us/cli/exchange.md
docs/en-us/cli/mesh.md
docs/en-us/cli/run.md
pkg/apiserver/util/cluster.go
pkg/kt/command/flags.go
pkg/kt/options/options.go

KubeConfig should load form env by default

---

pkg/kt/command/flags.go
pkg/kt/connect/inbound.go
pkg/kt/connect/outbound.go
pkg/kt/util/network.go

check local port is ready to speed up ktctl

---

pkg/kt/cluster/kubernetes.go
pkg/kt/cluster/kubernetes_test.go
pkg/kt/cluster/mock.go
pkg/kt/cluster/types.go
pkg/kt/cmd/connect.go
pkg/kt/command/connect.go
pkg/kt/command/flags.go
pkg/kt/options/options.go

add --global -g flag to connect command to support namespace scope

feat: #170 add --global support for connect with namespace scope

---

pkg/kt/cluster/helper.go

#170 add securityContext to shadow

feat: support openshift 4.x

---

pkg/proxy/dnsserver/dnsserver.go

Fix: resolve dns service.namespace.svc

---

Makefile
cmd/shadow/main.go
pkg/common/const.go
pkg/kt/command/connect.go

let shadow process listen to both socks and dns ports

---

pkg/kt/cmd/connect.go
pkg/kt/command/connect.go
pkg/kt/command/flags.go
pkg/kt/options/options.go

let connect auto dump service to hosts file on windows

---

.gitignore
pkg/kt/command/connect.go
pkg/kt/command/util.go
pkg/kt/connect/outbound.go
pkg/kt/registry/proxyconfig.go
pkg/kt/registry/registry.go
pkg/kt/registry/registry_windows.go

在WIndows下自动设置/还原全局HTTP_PROXY环境变量

auto setup windows proxy environment variable

---

build/docker/shadow/Dockerfile
build/docker/shadow/Dockerfile_base
build/docker/shadow/run.sh
build/docker/shadow/sshd_config
go.mod
go.sum
pkg/common/const.go
pkg/kt/cluster/helper.go
pkg/kt/cmd/connect.go
pkg/kt/command/connect.go
pkg/kt/command/connect_test.go
pkg/kt/command/flags.go
pkg/kt/command/util.go
pkg/kt/connect/outbound.go
pkg/kt/exec/mock.go
pkg/kt/exec/ssh/commands.go
pkg/kt/exec/ssh/mock.go
pkg/kt/exec/ssh/types.go
pkg/kt/exec/sshtunnelling/commands.go
pkg/kt/exec/sshtunnelling/doc.go
pkg/kt/exec/sshtunnelling/types.go
pkg/kt/exec/types.go
pkg/kt/options/options.go
pkg/kt/types.go
pkg/resolvconf/types.go

目前只支持linux
`ktclt  --image   xyzli/kt-connect-shadow:1627546125   connect  --method tun   --cidr 10.0.0.0/16  --tunCidr=10.1.2.0/30`
Fixes #228
/assign @linfan

add ssh tun mode

---

build/docker/shadow/run.sh
pkg/kt/command/connect.go
pkg/kt/connect/outbound.go
pkg/kt/exec/sshtunnelling/commands.go
pkg/kt/exec/sshtunnelling/types.go
pkg/kt/exec/types.go
pkg/kt/types.go

Signed-off-by: LiHui <andrewli@yunify.com>
` sudo ./ktctl --image  xyzli/kt-connect-shadow:1628133345  connect --method tun --cidr 10.0.0.0/16 --tunCidr=10.1.2.0/30`

replace route and ifconfig with ip

---

pkg/kt/cluster/helper.go
pkg/kt/command/flags.go
pkg/kt/options/options.go

add imagePullSecret option for private repository with authentication

feat: add imagePullSecret option

---

pkg/kt/exec/sshchannel/ssh.go

Fix: go routine leaks

---

pkg/kt/exec/sshuttle/commands.go

Signed-off-by: LiHui <andrewli@kubesphere.io>
Fixes: #253

fix nil writer

---

pkg/kt/connect/tunnel.go
pkg/kt/exec/portforward/portforward.go

Signed-off-by: LiHui <andrewli@kubesphere.io>

check localPort is whether in use or not.

---

docs/en-us/reference/comparison.md
docs/en-us/sidebar.md

It was translated using Google Translate. I've read the resulting translation and changed only a couple of words.

doc: add comparison to Telepresence in English

---

pkg/kt/service/cluster/configmap.go
pkg/kt/service/cluster/deployment.go
pkg/kt/service/cluster/heartbeat.go
pkg/kt/service/cluster/pod.go
pkg/kt/service/cluster/service.go

Fix concurrent map writes.
/cc @linfan

Fix: concurrent map writes

---

pkg/common/const.go
pkg/kt/command/connect/tun2socks.go
pkg/kt/command/general/setup.go
pkg/kt/command/options/global.go
pkg/kt/command/options/options.go
pkg/kt/command/options/store.go
pkg/kt/service/cluster/cidr.go
pkg/kt/service/tun/tun_windows.go
pkg/router/route.conf

add ipv6 support by kubeconfig apiserver IP type or command params

feat: support ipv6 address
